#数据库配置
jayud:
  datasource:
    ip: 113.100.140.250
    username: root
    password: Root!!2020
swagger:
  is:
    enable: true
#oms前缀路径
oms:
  content:
    path: /jayud-oms/
business:
  oms:
    datasource:
      name: jayud_platform

#oms前缀路径
oauth:
  content:
    path: /jayud-oauth/
#redis数据源
redis:
  server:
    url: 113.100.140.250
    port: 6377
    password: 'q$o8S#ixaf9x87nOF8oSoyAAQZut@zxe'